---

name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: docker build . -t  ${{ secrets.DOCKERHUB_USERNAME }}/snmpd:latest
      - name: Install Goss
        uses: e1himself/goss-installation-action@v1.1.0
      - name: Execute Goss tests
        run: dgoss run  ${{ secrets.DOCKERHUB_USERNAME }}/snmpd
      - name: Push Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/snmpd:latest

...
